name: menstrual_health_ai
description: "A menstrual health tracking app with AI features"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.1.2
  fl_chart: ^0.66.0
  table_calendar: ^3.0.9
  # flutter_local_notifications: 16.2.0  # Try a slightly older version
  path_provider: ^2.1.1
  pdf: ^3.10.7
  share_plus: ^7.2.1
  flutter_markdown: ^0.6.18
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_secure_storage: ^8.0.0
  flutter_animate: ^4.3.0
  lottie: ^2.7.0
  printing: ^5.11.0



#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.2
#   google_fonts: ^5.1.0
#   provider: ^6.0.5
#   intl: ^0.18.1
#   table_calendar: ^3.0.9
#   flutter_animate: ^4.2.0
#   fl_chart: ^0.63.0
#   lottie: ^2.6.0
#   shared_preferences: ^2.2.0
#   flutter_svg: ^2.0.7
#   smooth_page_indicator: ^1.1.0
#   http: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/hero.png

    # - .env




# name: menstrual_health_ai
# description: A menstrual health tracking app with AI features.
# publish_to: 'none'
# version: 1.0.0+1

# environment:
#   sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.2
#   google_fonts: ^5.1.0
#   provider: ^6.0.5
#   intl: ^0.18.1
#   table_calendar: ^3.0.9
#   flutter_animate: ^4.2.0
#   fl_chart: ^0.63.0
#   lottie: ^2.6.0
#   shared_preferences: ^2.2.0
#   flutter_svg: ^2.0.7
#   smooth_page_indicator: ^1.1.0
#   http: ^1.1.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
#     - assets/animations/
#     - assets/icons/
